# Generated by Django 3.2.9 on 2021-12-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_city_slug'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_stations',
            field=models.ManyToManyField(related_name='users', to='ui.Station'),
        ),
    ]
