# Generated by Django 3.2.9 on 2021-11-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название города')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug города')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название линии')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug линии')),
                ('hex_color', models.CharField(max_length=6, verbose_name='Название линии')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ui.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название станции')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug станции')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('latitude', models.FloatField(verbose_name='Долгота')),
                ('longitude', models.FloatField(verbose_name='Широта')),
                ('lines', models.ManyToManyField(to='ui.Line', verbose_name='Линии')),
            ],
        ),
    ]
