# Generated by Django 3.2.9 on 2021-11-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='lines',
        ),
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='ui.line', verbose_name='Линии'),
            preserve_default=False,
        ),
    ]
