# Generated by Django 3.2.9 on 2021-11-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20211115_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='slug',
        ),
    ]
