# Generated by Django 3.2.9 on 2021-11-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_remove_station_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='slug',
        ),
    ]
