# Generated by Django 3.2.9 on 2021-11-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_auto_20211121_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
