# Generated by Django 3.2.9 on 2021-12-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_remove_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Линия', 'verbose_name_plural': 'Линии'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
    ]
